name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: SonarCloud Analysis
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20  # Ustaw wersję zgodnie z Twoim projektem

      - name: Run Go Tests With Coverage
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          organization: product-app-ebiznes
          projectKey: product-app-ebiznes_sonar-test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

